# Theme options
tabs:
  fields:   
    ### Appearance            
    # Website Details
    appearance_settings_section:
      tab: Appearance
      label: Website Details
      span: left
      type: section
    
    # Header Settings
    appearance_header_section:
      tab: Appearance
      label: Header Settings
      span: right
      type: section  
    
    site_name:
      tab: Appearance
      span: left
      label: Site name
      type: text  
    
    frontend_header_type:
      tab: Appearance
      span: right
      label: Select type of Header for Frontpage
      type: dropdown
      showSearch: false
      placeholder: -- select a header type --
      options:
        image: Image
        slideshow: Slideshow
        video: Video
        
    main_slider:
      tab: Appearance
      span: right
      label: Header Slideshow
      type: repeater
      cssClass: form_container
      form:
        fields:
          title:
            span: left
            label: Title
            type: text
          subtitle:
            span: right
            label: Sub-Title
            type: text
          link:
            span: left
            label: Link URL
            type: text
          linktext:
            span: right
            label: Link Text
            type: text
          image:
            span: full
            label: Select Image
            type: mediafinder
            mode: image
    main_image:
      tab: Appearance
      span: right
      label: Header Image
      type: mediafinder
      mode: image
      cssClass: form_container
    main_video:
      tab: Appearance
      span: right
      label: Header Video
      type: text
      cssClass: form_container
    
    
      
    ## Block Features
    block_features:
      tab: Features
      span: full
      label: Tick to activate the "Features" block on your frontpage
      comment: This Block shows a set of Features with an icon, title and text. For the best appearance, you need to use exactly 4 Feature items. Choose icons from here www.rhythm.nikadevs.com/content/icons-et-line.
      type: switch
      on: On
      off: Off
    
    # Features Form
    block_features_repeater:
      tab: Features
      span: full
      label: Feature items
      type: repeater
      prompt: Add feature
      form:
        fields:
            feature_icon:
              tab: Features
              span: left
              label: Icon
              type: text
                
            feature_title:
              tab: Features
              span: right
              label: Title
              type: text  
            feature_text:
              tab: Features
              span: full
              label: Description
              type: richeditor
    
    
      
    ## Block About
    block_about:
      tab: About us
      span: full
      label: Tick to activate the "About us" block on your frontpage
      type: switch
      on: On
      off: Off
    
    # About us Form
    about_title:
      tab: About us
      span: left
      label: Title
      type: text
    about_image:
      tab: About us
      span: right
      label: Image
      type: mediafinder
      mode: image
    about_subtitle:
      tab: About us
      span: left
      label: Sub-Title
      type: text
    about_description:
      tab: About us
      span: left
      label: Description
      type: richeditor
    
    
      
    ## Block Our work    
    # Our work Form
    block_work:
      tab: Our work
      span: left
      label: Tick to activate the "Our work" block on your frontpage
      type: switch
      on: On
      off: Off
    
    block_work_repeater:
      tab: Our work
      span: right
      label: Items
      type: repeater
      prompt: Add work item
      form:
        fields:                
            work_title:
              tab: Our work
              span: left
              label: Title
              type: text
            work_image:
              tab: Our work
              span: right
              label: Image
              type: mediafinder
              mode: image  
            work_subtitle:
              tab: Our work
              span: left
              label: Sub-title
              type: text  
            work_link:
              tab: Our work
              span: left
              label: Link
              type: text  
            work_sortclass:
              tab: Our work
              span: full
              label: Sortable class name
              type: text
    block_work_title:
      tab: Our work
      span: left
      label: Title
      type: text
    
    
      
    ## Block Callout    
    # Callout Form
    block_callout:
      tab: Callout
      span: left
      label: Tick to activate the "Callout" block on your frontpage
      type: switch
      on: On
      off: Off
      
    callout_title:
      tab: Callout
      span: left
      label: Title
      type: text
    callout_linkname:
      tab: Callout
      span: right
      label: Linkname
      type: text  
    callout_subtitle:
      tab: Callout
      span: left
      label: Sub-Title
      type: text
    callout_linktarget:
      tab: Callout
      span: right
      label: URL
      type: text
    
    
      
    ## Block Team    
    # Team Form
    block_team:
      tab: Team
      span: left
      label: Tick to activate the "Team" block on your frontpage
      type: switch
      on: On
      off: Off
    
    block_team_repeater:
      tab: Team
      span: right
      label: Items
      type: repeater
      form:
        fields:
            team_personal_information:
              tab: Team
              label: Personal information
              span: full
              type: section                
            team_name:
              tab: Team
              span: left
              label: Name
              type: text
            team_image:
              tab: Team
              span: right
              label: Image
              type: mediafinder
              mode: image  
            team_position:
              tab: Team
              span: left
              label: Position
              type: text  
            team_title:
              tab: Team
              span: left
              label: Title
              type: text  
            team_description:
              tab: Team
              span: left
              label: Description
              type: text
            team_social_information:
              tab: Team
              label: Social information
              span: full
              type: section                
            team_facebook:
              tab: Team
              span: left
              label: Facebook
              type: text                
            team_twitter:
              tab: Team
              span: right
              label: Twitter
              type: text                
            team_instagram:
              tab: Team
              span: left
              label: Instagram
              type: text                
            team_linkedin:
              tab: Team
              span: right
              label: Linkedin
              type: text                
            team_pinterest:
              tab: Team
              span: left
              label: Pinterest
              type: text
    block_team_title:
      tab: Team
      span: left
      label: Title
      type: text
    block_team_subtitle:
      tab: Team
      span: left
      label: Sub-Title
      type: text
        
    ## Block FAQ    
    # FAQ Form
    block_faq:
      tab: FAQ&Skills
      span: left
      label: Tick to activate the "FAQ" block on your frontpage
      type: switch
      on: On
      off: Off
    block_skills:
      tab: FAQ&Skills
      span: right
      label: Tick to activate the "Skills" block on your frontpage
      type: switch
      on: On
      off: Off
      
    faq_section:
      tab: FAQ&Skills
      span: left
      label: FAQ
      type: section
    skills_section:
      tab: FAQ&Skills
      span: right
      label: Skills
      type: section
        
    block_faq_title:
      tab: FAQ&Skills
      span: left
      label: Title
      type: text
    block_skills_title:
      tab: FAQ&Skills
      span: right
      label: Title
      type: text
      
    block_faq_repeater:
      tab: FAQ&Skills
      span: left
      label: FAQ
      type: repeater
      prompt: Add new FAQ
      form:
        fields:
            faq_unique:
              tab: FAQ&Skills
              label: Unique name
              span: left
              type: text
            faq_question:
              tab: FAQ&Skills
              label: Question
              span: full
              type: text
            faq_answer:
              tab: FAQ&Skills
              label: Answer
              span: full
              type: richeditor  

      
    block_skills_repeater:
      tab: FAQ&Skills
      span: right
      label: Skills
      type: repeater
      prompt: Add new Skill
      form:
        fields:
            skill_name:
              tab: FAQ&Skills
              label: Name
              span: left
              type: text
            skill_icon:
              tab: FAQ&Skills
              label: ET-Line Icon
              span: right
              type: text
            skill_min:
              tab: FAQ&Skills
              label: Min value
              span: storm
              type: text
              cssClass: col-sm-4
            skill_max:
              tab: FAQ&Skills
              label: Max value
              span: storm
              type: text
              cssClass: col-sm-4
            skill_value:
              tab: FAQ&Skills
              label: Value
              span: storm
              type: text
              cssClass: col-sm-4   
        
    ## Block Testimonials    
    # Testimonials Form
    block_testimonials:
      tab: Testimonials
      span: left
      label: Tick to activate the "Testimonials" block on your frontpage
      type: switch
      on: On
      off: Off
    
    block_testimonials_repeater:
      tab: Testimonials
      span: right
      label: Testimonials
      type: repeater
      form:
        fields:
            testimonial_name:
              tab: Testimonials
              label: Name
              span: left
              type: text                
            testimonial_company:
              tab: Testimonials
              span: right
              label: Company
              type: text
            testimonial_text:
              tab: Testimonials
              span: full
              label: Text
              type: richeditor
    block_testimonials_image:
      tab: Testimonials
      span: left
      label: Background image
      type: mediafinder
      mode: image
      
    # Company details  
    company_details_section:
      tab: Company details
      label: Company details
      span: left
      type: section  
    contact_details_section:
      tab: Company details
      label: Contact information
      span: right
      type: section
          
    company_title:
      tab: Company details
      span: left
      label: Company Widget Title
      type: text
    contact_phone:
      tab: Company details
      span: right
      label: Contact Phone
      type: text
           
    company_slogan:
      tab: Company details
      span: left
      label: Company Widget Slogan
      type: text
    contact_fax:
      tab: Company details
      span: right
      label: Contact Fax
      type: text
            
    company_name:
      tab: Company details
      span: left
      label: Company Name
      type: text
    contact_address:
      tab: Company details
      span: right
      label: Contact Address
      type: text
        
    company_description:
      tab: Company details
      span: left
      label: Company Description
      type: text      
    contact_address2:
      tab: Company details
      span: right
      label: Contact Address 2
      type: text
      
    contact_email:
      tab: Company details
      span: right
      label: Contact Email
      type: text      
    copyright:
      tab: Company details
      span: left
      label: Copyright
      type: text  
   
    # Social links
    social_facebook:
      tab: Social
      span: left
      label: Facebook link
      type: text
    social_twitter:
      tab: Social
      span: left
      label: Twitter link
      type: text
    social_instagram:
      tab: Social
      span: left
      label: Instagram link
      type: text
    social_linkedin:
      tab: Social
      span: left
      label: Linkedin link
      type: text
    social_pinterest:
      tab: Social
      span: left
      label: Pinterest link
      type: text
      
    load_file:
      tab: Social
      span: left
      type: partial
      path: ~/themes/liath-chamy/config/_load_file.htm